name: travel_data_platform
version: 1.0.0
config-version: 2

profile: dbt_project

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  source_schema: BRONZE
  target_database: TRAVEL_DW

models:
  travel_data_platform:
    +database: "{{ var('target_database') }}"
    staging:
      +materialized: view
      +schema: SILVER
    intermediate:
      +materialized: view
      +schema: SILVER
    marts:
      +materialized: table
      +schema: GOLD
