apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.8.4-python3.11
          command: ["/bin/bash", "-c"]
          args:
            - >
              export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://travel_user:${POSTGRES_PASSWORD}@postgres:5432/travel_db";
              airflow db migrate;
              airflow webserver
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: travel-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: apache/airflow:2.8.4-python3.11
          command: ["/bin/bash", "-c"]
          args:
            - >
              export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://travel_user:${POSTGRES_PASSWORD}@postgres:5432/travel_db";
              airflow scheduler
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: travel-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: NodePort
  selector:
    app: airflow
    component: webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
